export default [
    'Die Hard',
    'The Transporter',
    'The Dark Knight',
    'The Bourne Identity',
    'Suicide Squad',
    'Hancock',
    'The Terminator',
    'Predator',
    'Taken',
    'Mission Impossible',
    'Gladiator',
    'Lethal Weapon',
    'Tomb Raider',
    'Anchorman',
    'Superbad',
    'The Other Guys',
    'Step Brothers',
    'Liar Liar',
    'Knocked Up',
    'Zoolander',
    'Tropic Thunder',
    'Dodgeball',
    'Old School',
    'Ghostbusters',
    'The Big Lebowski',
    'Dumb and Dumber',
    'Meet the Fockers',
    'The Shining',
    'Paranormal Activity',
    'Scream',
    'The Conjuring',
    'The Cabin in the Woods',
    'The Exorcist',
    'The Human Centipede',
    'The Blair Witch Project',
    'Jaws',
    'Dawn of the Dead',
    'Halloween',
    'Ring',
    'The Texas Chain Saw Massacre',
    'The Silence of the Lambs',
    'Inception',
    'The Departed',
    'Heat',
    'The Dark Knight Rises',
    'Black Swan',
    'The Bourne Ultimatum',
    'No Country for Old Men',
    'The Fugitive',
    'Shutter Island',
    'Mystic River',
    'The Others',
    'Sin City']