export default [
    'Johnny Depp',
    'Arnold Schwarzenegger',
    'Jim Carrey',
    'Emma Watson',
    'Daniel Radcliffe',
    'Leonardo DiCaprio',
    'Tom Cruise',
    'Brad Pitt',
    'Charles Chaplin',
    'Morgan Freeman',
    'Tom Hanks',
    'Hugh Jackman',
    'Matt Damon',
    'Sylvester Stallone',
    'Will Smith',
    'Clint Eastwood',
    'Cameron Diaz',
    'George Clooney',
    'Steven Spielberg',
    'Harrison Ford',
    'Robert De Niro',
    'Al Pacino',
    'Robert Downey Jr',
    'Russell Crowe',
    'Liam Neeson',
    'Kate Winslet',
    'Mark Wahlberg',
    'Natalie Portman',
    'Pierce Brosnan',
    'Sean Connery',
]